### ISSUE TITLE
The val_acc of this model is 0

### ISSUE THREAD

**Issue by wongsihan** [PacktPublishing/Hands-On-Meta-Learning-with-Python#3]
Hi, thank you for sharing code, I set epochs more than 300  and when it equals to 32, the accuracy is 25%, and this is the max value, is that correct? and during the whole process, the val_acc is 0.

**Comment by wongsihan** [comment]
I mean Chapter 2 siamese network for audio processing

**Comment by gaurav-packt** [comment]
Please reopen if the issue persists.
